name: Build

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to build with'
        required: true
        type: string
        default: '3.10'
      os:
        description: 'OS to build on'
        required: true
        type: string
        default: 'ubuntu-latest'

jobs:
  build:
    name: Build Package
    runs-on: ${{ inputs.os || github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ inputs.python-version || github.event.inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || github.event.inputs.python-version }}
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          
      - name: Install the project
        run: uv sync --all-extras --dev
        
      - name: Build package
        run: uv build 