name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to test with'
        required: true
        type: string
        default: '3.10'
      os:
        description: 'OS to test on'
        required: true
        type: string
        default: 'ubuntu-latest'

jobs:
  test:
    name: Run Tests
    runs-on: ${{ inputs.os || github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ inputs.python-version || github.event.inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || github.event.inputs.python-version }}
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          
      - name: Install the project
        run: uv sync --all-extras --dev
        
      - name: Install tox
        run: pip install tox
        
      - name: Run tox
        run: |
          PY_VERSION=$(echo ${{ inputs.python-version || github.event.inputs.python-version }} | tr -d '.')
          tox -e py$PY_VERSION 